#!/bin/bash

# LogHandler for SetupHelper
# contains a functions and variables necessarey to write to and output logs
#
# Refer to the SetupHelper ReadMe file for details on how to use these resources
#

logDir="/var/log/PackageManager"
logFile="$logDir/current"
if ! [ "$logDir" ]; then
	mkdir -P "$logDir"
	touch "$logFile"
fi

oldLogFile="/var/log/SetupHelper"
if [ -e "$oldLogFile" ]; then
	if (( $( tail -5 "$oldLogFile" | grep -c "WARNING: this log file no longer used" ) == 0 )); then
		echo "WARNING: this log file no longer used" >> "$oldLogFile"
		echo "      SetupHelper now logged to /var/log/PackageManager/current" >> "$oldLogFile"
	fi
fi

# enable logging to console
# scripts can disable logging by setting 
# logToConsole to false AFTER sourcing LogHandler
logToConsole=true

# output the last 100 lines of the log file to the console
# the full path to the log file should be passed in $1
# converts the tai64 time stamp to human readable form

displayLog ()
{
	tail -100 "$logFile" | tai64nlocal
}


# write a message to log file and console

logMessage ()
{
    # to console
    if $logToConsole ; then
        echo "$*"
    fi

    # to setup helper log
	echo "$shortScriptName: $*" | tai64n >> $logFile
}
