#!/bin/bash

# this script is part of an autoInstall archive
# the archive makes use of the Venus OS update-data.sh script
# archives named "venus-data.tar" are unpacked during boot
# then for this archive, Venus must be rebooted, causing rcS.local to run,
# which calls blindInstall as a background task.
#
# Package install scripts will append to rcS.local, so it must be moved out of the way
# BEFORE running those scripts to force creation of a clean rcS.local
#
# GitHub automatic updates are enabled to keep packages up to date.
#
# the archive includes
#   rcS.local and the packages themselves
# 
# the blindInstall script is run in the background so it can wait for dbus Settings resources
# to become available before running the package install scripts.
#

source "/data/SetupHelper/EssentialResources"
source "/data/SetupHelper/LogHandler"

# wait until dbus settings are active
while [ $(dbus -y | grep -c "com.victronenergy.settings") == 0 ]; do
    logMessage "waiting for dBus settings"
    sleep 1
done

logMessage "starting up"

# a package setup script normally prompts for user input
# reinstall force options insure the package is installed without user interaction
#
# currently VeCanSetup and RpiDisplaySetup require user responses during initial setup
# so can't be installed via this mechanism

# all packages rely on SetupHelper so it must be present and installed first
if [ -f "/data/SetupHelper/setup" ]; then
    # insure package reinstall doesn't get appended to the auto install rcS.local !!!
    rm -f /data/rcS.local
    sync
    logMessage "installing SetupHelper"
    /data/SetupHelper/setup reinstall force deferReboot
    if [ -f "/data/GuiMods2/setup" ]; then
        logMessage "installing GuiMods2"
        /data/GuiMods2/setup reinstall force deferReboot
    fi

    # enable GitHub automatic updates
    dbus -y com.victronenergy.settings /Settings/GuiMods/GitHubAutoUpdate SetValue 1 &> /dev/null
fi

