#!/bin/bash

# this script will install any package that can use
# the automated install and uninstall mechanisms provided by SetupHelper
# that is, no custom prompting for command line exection
#	and no custom installation such as editing replacement files
#
# link the package's setup script to this one:
#	ln -s /data/SetupHelper/genericSetupScript /data/<package name>/setup

# tell CommonResources to:
#	prompt for install/uninstall
#	auto install or auto uninstall
#	then exit
#	CommonResources will NOT return here !

standardPromptAndActions='yes'

#### following line incorporates helper resources into this script
source "/data/SetupHelper/HelperResources/IncludeHelpers"
#### end of lines to include helper resources

# never returns from CommonResources !
