#!/bin/sh

# reinstalMods will reinstall SetupHelper if a Venus OS update removes it
#
# other packages will then be reinstalled by PackageManager
#

# this script is called from /data/rcS.local during system boot
# it checks to see if SetupHelper and the PackageManager service
#	are installed and if not, will install the PackageManager service
#
# the REINSTALL_PACKAGES flag file is then set so that when
#	PackageManger runs, it will do boot-time reinstall checks of all packages

scriptDir="$( cd "$(dirname $0)" >/dev/null 2>&1 ; /bin/pwd -P )"
helperResourcesDir="$scriptDir/HelperResources"
source "$helperResourcesDir/EssentialResources"
source "$helperResourcesDir/LogHandler"

# disable outputting log messages to console
runningAtBoot=true

logMessage "reinstallMods starting"









command="$scriptDir/setup"

installSetupHelper=true
# SetupHelper already installed, nothing to do
if [ -f "$installedVersionFile" ]; then
	logMessage "SetupHelper already installed"
	installSetupHelper=false
elif [ -f "$setupOptionsDir/DO_NOT_AUTO_INSTALL" ]; then
	logMessage "CRITICAL: SetupHelper was manually uninstalled therefore it was not reinstalled"
	logMessage "    other packages will NOT BE REINSTALLED either !"
	installSetupHelper=false
elif ! [ -f $command ] ; then
	logMessage "ERROR: SetupHelper setup script not found - can't reinstall"
	installSetupHelper=false
fi

rebootNeeded=false

if $installSetupHelper; then
	# hold off PackageManager processing
	#	this is unlikely since SetupHelper isn't installed yet
	touch "/etc/venus/REINSTALL_MODS_RUNNING"
	waitReported=false
	# wait until PM is no longer running
	#	or is waiting for this script to finish
	while true ; do
		if [ -n $( pgrep -f PackageManager.py ) ]; then
			pmStatus=$( dbus -y com.victronenergy.packageManager /PmStatus GetValue )
			if [[ "$pmStatus" == *"boot reinstall"* ]]; then
				if $waitReported ; then
					logMessage "PackageManager waiting for reinstallMods to finish"
				fi
				break
			elif ! $waitReported ; then
				logMessage "waiting for PackageManager to complete operations"
				waitReported=true
			fi
		else
			if $waitReported ; then
				logMessage "PackageManager no longer running"
			fi
			break
		fi
		sleep 2
	done

	# run setup script
	installOtherPackages=false
	$command reinstall auto deferReboot
	returnCode=$?

	case $returnCode in
		$EXIT_SUCCESS )
			installOtherPackages=true
			;;
		$EXIT_REBOOT )
			installOtherPackages=true
			rebootNeeded=true
			;;
		$EXIT_NO_GUI_V1 )
			logMessage "ERROR: SetupHelper install failed - no GUI v1 installed"
			;;
		$EXIT_ROOT_FULL )
			logMessage "ERROR: SetupHelper install failed - no room in root partition"
			;;
		*)
			logMessage "ERROR: SetupHelper install failed - reason $returnCode"
			;;
	esac

	if $installOtherPackages ; then
		logMessage "SetupHelper installed - PackageManager will reinstall remaining packages"
		# flag file is cleared in PackageManager when all install checks have been made
		touch "/etc/venus/REINSTALL_PACKAGES"
	fi
fi

# reboot now if signaled from setup script
# if rebooting, PackageManager processing will be held until
#	this script runs on next boot and clears the flag below.
if $rebootNeeded ; then
    logMessage "rebooting ..."
    reboot
# allow PackageManager to continue processing
else
	rm -f "/etc/venus/REINSTALL_MODS_RUNNING"
	logMessage "reinstallMods finished"
fi

