#!/bin/sh

# reinstalMods will reinstall customizations to Venus following a software update
#
# some setup scripts access dbus Settings which are not up early in the boot process
# therefore, this script is run as a background task and waits for dbus Settings
#

setupHelperDir="/data/SetupHelper"
source "$setupHelperDir/EssentialResources"
source "$scriptDir/LogHandler"

# disable outputting log messages to console
runningAtBoot=true

if [ ! -f "$reinstallScriptsList" ] ; then
    logMessage "$reinstallScriptsList file not found"
    exit
fi

logMessage "reinstallMods starting"

# read lines from script list file specified above
# and call each script
rebootNeeded=false
guiRestartNeeded=false
okToInstall=false

while read -u 9 line ; do
    # ignore blank and comment lines
    if [ ! -z "$line" ] && ! [[ "$line" == \#* ]]; then
        # strip command parameters and add new ones here
        command=$(awk '{print var $1}' <<< $line)
		scriptDir=$(dirname $command)
		packageName=$(basename $scriptDir)
		if [ ! -f $command ] ; then
			logMessage "Error: $packageName setup script not found - skipping reinstall"
			continue
		fi

		packageVersionFile="$scriptDir/version"
		installedVersionFile="$installedVersionPrefix$packageName"
		doReinstall=false
		# call setup script if versions are different or package not currently installed
		if [ -f "$installedVersionFile" ]; then
			installedVersion=$(cat "$installedVersionFile")
		else
			installedVersion=""
			doReinstall=true
		fi
		if [ -f "$packageVersionFile" ]; then
			packageVersion=$(cat "$packageVersionFile")
		else
			packageVersion=""
		fi
		if [ "$packageVersion" != "$installedVersion" ]; then
			doReinstall=true
		fi

        if $doReinstall ; then
			# wait until dbus settings and GUI are active before calling setup script
			#	this is done before first reinstall so PackageManager isn't held off if there are no reinstalls
			while ! $okToInstall ; do
				if [ $(dbus -y | grep -c "com.victronenergy.settings") == 0 ]; then
					logMessage "waiting for dBus settings"
					sleep 2
				else
					okToInstall=true
				fi
			done

			# run setup script
			fullCommand=$(echo "$command reinstall auto deferReboot deferGuiRestart")
			$fullCommand
			returnCode=$?
			if (( $returnCode == $EXIT_REBOOT )) ; then
				logMessage "$packageName reinstall requested reboot"
				rebootNeeded=true
			elif (( $returnCode == $EXIT_RESTART_GUI )) ; then
				logMessage "$packageName reinstall requested GUI restart"
				guiRestartNeeded=true
			fi
		fi
    fi
done 9< "$reinstallScriptsList"

logMessage "reinstallMods complete"

# reboot or restart GUI now if any script reboots were indicated
if $rebootNeeded ; then
    logMessage "rebooting ..."
    reboot
elif $guiRestartNeeded ; then
    logMessage "restarting GUI"
    restartGuiService
fi

