#!/bin/bash


# remove Settings associated with previous versions of SetupHelper
# and those of the current verison
# run this script to make a clean start

source /data/SetupHelper/DbusSettingsResources

removeDbusSettings	/Settings/PackageManager/Count \
					/Settings/PackageManager/GitHubAutoUpdate \
					/Settings/PackageManager/GitHubAutoDownload \
					/Settings/PackageManager/AutoInstall \
					/Settings/PackageManager/Edit/PackageName \
					/Settings/PackageManager/Edit/GitHubUser \
					/Settings/PackageManager/Edit/GitHubBranch \
					/Settings/PackageManager/0/PackageName \
					/Settings/PackageManager/0/GitHubUser \
					/Settings/PackageManager/0/GitHubBranch \
					/Settings/PackageManager/1/PackageName \
					/Settings/PackageManager/1/GitHubUser \
					/Settings/PackageManager/1/GitHubBranch \
					/Settings/PackageManager/2/PackageName \
					/Settings/PackageManager/2/GitHubUser \
					/Settings/PackageManager/2/GitHubBranch \
					/Settings/PackageManager/3/PackageName \
					/Settings/PackageManager/3/GitHubUser \
					/Settings/PackageManager/3/GitHubBranch \
					/Settings/PackageManager/4/PackageName \
					/Settings/PackageManager/4/GitHubUser \
					/Settings/PackageManager/4/GitHubBranch > /dev/null

removeDbusSettings	/Settings/PackageManager/5/PackageName \
					/Settings/PackageManager/5/GitHubUser \
					/Settings/PackageManager/5/GitHubBranch \
					/Settings/PackageManager/6/PackageName \
					/Settings/PackageManager/6/GitHubUser \
					/Settings/PackageManager/6/GitHubBranch \
					/Settings/PackageManager/7/PackageName \
					/Settings/PackageManager/7/GitHubUser \
					/Settings/PackageManager/7/GitHubBranch \
					/Settings/PackageManager/8/PackageName \
					/Settings/PackageManager/8/GitHubUser \
					/Settings/PackageManager/8/GitHubBranch \
					/Settings/PackageManager/9/PackageName \
					/Settings/PackageManager/9/GitHubUser \
					/Settings/PackageManager/9/GitHubBranch > /dev/null

removeDbusSettings	/Settings/PackageManager/10/PackageName \
					/Settings/PackageManager/10/GitHubUser \
					/Settings/PackageManager/10/GitHubBranch \
					/Settings/PackageManager/11/PackageName \
					/Settings/PackageManager/11/GitHubUser \
					/Settings/PackageManager/11/GitHubBranch \
					/Settings/PackageManager/12/PackageName \
					/Settings/PackageManager/12/GitHubUser \
					/Settings/PackageManager/12/GitHubBranch \
					/Settings/PackageManager/13/PackageName \
					/Settings/PackageManager/13/GitHubUser \
					/Settings/PackageManager/13/GitHubBranch \
					/Settings/PackageManager/14/PackageName \
					/Settings/PackageManager/14/GitHubUser \
					/Settings/PackageManager/14/GitHubBranch > /dev/null

removeDbusSettings	/Settings/PackageManager/15/PackageName \
					/Settings/PackageManager/15/GitHubUser \
					/Settings/PackageManager/15/GitHubBranch \
					/Settings/PackageManager/16/PackageName \
					/Settings/PackageManager/16/GitHubUser \
					/Settings/PackageManager/16/GitHubBranch \
					/Settings/PackageManager/17/PackageName \
					/Settings/PackageManager/17/GitHubUser \
					/Settings/PackageManager/17/GitHubBranch \
					/Settings/PackageManager/18/PackageName \
					/Settings/PackageManager/18/GitHubUser \
					/Settings/PackageManager/18/GitHubBranch \
					/Settings/PackageManager/19/PackageName \
					/Settings/PackageManager/19/GitHubUser \
					/Settings/PackageManager/19/GitHubBranch > /dev/null
