#!/bin/bash


# remove Settings associated with previous versions of SetupHelper
# and those of the current verison
# run this script to make a clean start

source /data/SetupHelper/DbusSettingsResources

removeDbusSettings	/Settings/PackageMonitor/Count \
					/Settings/PackageMonitor/GitHubAutoUpdate \
					/Settings/PackageMonitor/GitHubAutoDownload \
					/Settings/PackageMonitor/AutoInstall \
					/Settings/PackageMonitor/Edit/PackageName \
					/Settings/PackageMonitor/Edit/GitHubUser \
					/Settings/PackageMonitor/Edit/GitHubBranch \
					/Settings/PackageMonitor/0/PackageName \
					/Settings/PackageMonitor/0/GitHubUser \
					/Settings/PackageMonitor/0/GitHubBranch \
					/Settings/PackageMonitor/1/PackageName \
					/Settings/PackageMonitor/1/GitHubUser \
					/Settings/PackageMonitor/1/GitHubBranch \
					/Settings/PackageMonitor/2/PackageName \
					/Settings/PackageMonitor/2/GitHubUser \
					/Settings/PackageMonitor/2/GitHubBranch \
					/Settings/PackageMonitor/3/PackageName \
					/Settings/PackageMonitor/3/GitHubUser \
					/Settings/PackageMonitor/3/GitHubBranch \
					/Settings/PackageMonitor/4/PackageName \
					/Settings/PackageMonitor/4/GitHubUser \
					/Settings/PackageMonitor/4/GitHubBranch > /dev/null

removeDbusSettings	/Settings/PackageMonitor/5/PackageName \
					/Settings/PackageMonitor/5/GitHubUser \
					/Settings/PackageMonitor/5/GitHubBranch \
					/Settings/PackageMonitor/6/PackageName \
					/Settings/PackageMonitor/6/GitHubUser \
					/Settings/PackageMonitor/6/GitHubBranch \
					/Settings/PackageMonitor/7/PackageName \
					/Settings/PackageMonitor/7/GitHubUser \
					/Settings/PackageMonitor/7/GitHubBranch \
					/Settings/PackageMonitor/8/PackageName \
					/Settings/PackageMonitor/8/GitHubUser \
					/Settings/PackageMonitor/8/GitHubBranch \
					/Settings/PackageMonitor/9/PackageName \
					/Settings/PackageMonitor/9/GitHubUser \
					/Settings/PackageMonitor/9/GitHubBranch > /dev/null

removeDbusSettings	/Settings/PackageMonitor/10/PackageName \
					/Settings/PackageMonitor/10/GitHubUser \
					/Settings/PackageMonitor/10/GitHubBranch \
					/Settings/PackageMonitor/11/PackageName \
					/Settings/PackageMonitor/11/GitHubUser \
					/Settings/PackageMonitor/11/GitHubBranch \
					/Settings/PackageMonitor/12/PackageName \
					/Settings/PackageMonitor/12/GitHubUser \
					/Settings/PackageMonitor/12/GitHubBranch \
					/Settings/PackageMonitor/13/PackageName \
					/Settings/PackageMonitor/13/GitHubUser \
					/Settings/PackageMonitor/13/GitHubBranch \
					/Settings/PackageMonitor/14/PackageName \
					/Settings/PackageMonitor/14/GitHubUser \
					/Settings/PackageMonitor/14/GitHubBranch > /dev/null

removeDbusSettings	/Settings/PackageVersion/Count \
					/Settings/PackageVersion/New/GitHubUser \
					/Settings/PackageVersion/New/GitHubBranch \
					/Settings/PackageVersion/New/InstalledVersion \
					/Settings/PackageVersion/New/PackageName \
					/Settings/PackageVersion/New/PackageVersion \
					/Settings/PackageVersion/EditPackageIndex \
					/Settings/PackageVersion/GitHubAutoUpdate \
					/Settings/PackageVersion/GitHubAutoUpdate \
					/Settings/PackageVersion/EditAction \
					/Settings/PackageVersion/CheckingPackage \
					/Settings/PackageVersion/0/PackageName \
					/Settings/PackageVersion/0/GitHubUser \
					/Settings/PackageVersion/0/GitHubBranch \
					/Settings/PackageVersion/0/GitHubVersion \
					/Settings/PackageVersion/0/InstalledVersion \
					/Settings/PackageVersion/0/PackageVersion  > /dev/null
removeDbusSettings	/Settings/PackageVersion/1/PackageName \
					/Settings/PackageVersion/1/GitHubUser \
					/Settings/PackageVersion/1/GitHubBranch \
					/Settings/PackageVersion/1/GitHubVersion \
					/Settings/PackageVersion/1/InstalledVersion \
					/Settings/PackageVersion/1/PackageVersion \
					/Settings/PackageVersion/2/PackageName \
					/Settings/PackageVersion/2/GitHubUser \
					/Settings/PackageVersion/2/GitHubBranch \
					/Settings/PackageVersion/2/GitHubVersion \
					/Settings/PackageVersion/2/InstalledVersion \
					/Settings/PackageVersion/2/PackageVersion \
					/Settings/PackageVersion/3/PackageName \
					/Settings/PackageVersion/3/GitHubUser \
					/Settings/PackageVersion/3/GitHubBranch \
					/Settings/PackageVersion/3/EditAction \
					/Settings/PackageVersion/3/GitHubVersion \
					/Settings/PackageVersion/3/InstalledVersion \
					/Settings/PackageVersion/3/PackageVersion  > /dev/null
