#!/bin/bash

# SetupHelper provides a set of utilities used by other packages to streamline installing and removing packages
#	and facilitates reinstallation following a Venus OS update
# package setup scripts can be run from the command line for manual installation and uninstallation,
#	and in some cases inputing configuration options
#
# SetupHelper includes PackageManager which manages package updates from GitHub
# 	as well as package installation an uninstallation from the main GUI
#
# this setup script does NOT use version-dependent file sets
# 	rather it makes modifications as part of this script
#	so that updates are not required when Venus OS versions are added

# tell CommonResources to:
#	prompt for install/uninstall
#	auto install or auto uninstall
#	then exit
#	CommonResources will NOT return here !

standardPromptAndActions='yes'

#rebootNeeded=true
#### following line incorporates helper resources into this script
source "/data/SetupHelper/HelperResources/IncludeHelpers"
#### end of lines to include helper resources
